language: c
dist: bionic

matrix:
  include:

  # #### CPU formats test (gcc)
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages: &required
          # John the Ripper required stuff
          - libssl-dev
          - zlib1g-dev
          # Extra formats and performance
          - yasm
          - libgmp-dev
          - libpcap-dev
          - pkg-config
          - libbz2-dev
          # OpenMP for clang
          - libiomp-dev

  # #### CPU formats test (clang)
  - os: linux
    compiler: clang
    addons:
      apt:
        packages: *required

  # #### OpenCL formats test. Use Trusty (fglrx driver)
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        packages:
          # John the Ripper required stuff
          - libssl-dev
          - zlib1g-dev
          # Extra formats and performance
          - yasm
          - libgmp-dev
          - libpcap-dev
          - pkg-config
          - libbz2-dev
          # OpenMP for clang
          - libiomp-dev
          # OpenCL
          - fglrx-dev
          - opencl-headers
    env: OPENCL="yes"

  # #### MacOS CPU plus OpenCL formats test
  - os: osx
    osx_image: xcode8.3
    env: OPENCL="yes"

  # #########################################
  # #### Extra Testing Scheme
  # #########################################

  # #### OpenCL formats Docker based testing
  - if: branch = bleeding-jumbo
    os: linux
    compiler: gcc
    env: DOCKER="yes" OPENCL="yes"

script:
  - .travis/travis-ci.sh
